name: Bug Report
description: File a bug report against nextest.
title: "[bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report! Please fill out the sections below to help us reproduce
        and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      description: |
        Describe the issue including steps to reproduce.
      value: |
        **Description:**

        **Steps to reproduce:**
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected outcome
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: What actually happened? Include as much output as possible, using a [gist](https://gist.github.com) if necessary.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Nextest version
      description: Paste the output of `cargo nextest --version`. Please ensure you're using [the latest version](https://nexte.st/changelog/).
      render: text
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        Add other context about the problem here. For example, do you have a higher-level goal in mind? Is your setup special in any way?
    validations:
      required: false
